spring:
  application:
    name: ms-transferer
  servlet:
    context-path: /ms-transferer
  data:
    mongodb:
      uri: mongodb+srv://lucio2022:lucio123@bootcamp-may.ucmqo.mongodb.net/Bootcamp-May?retryWrites=true&w=majority

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${COMPUTERNAME:localhost}

server:
  port: 8086

resilience4j:
  circuitbreaker:
    instances:
      transferer:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        timeoutDuration: 2s
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
