spring:
  application:
    name: ms-transferer
  servlet:
    context-path: /ms-transferer
  data:
    mongodb:
      uri: mongodb+srv://lucio2022:lucio123@bootcamp-may.ucmqo.mongodb.net/Bootcamp-May?retryWrites=true&w=majority

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${COMPUTERNAME:localhost}

server:
  port: 8086
